
  CREATE TABLE "COUNTRIES" 
   (	"CCA2" VARCHAR2(2), 
	"FLAG" VARCHAR2(100), 
	"NAME_COMMON" VARCHAR2(255), 
	"NAME_OFFICIAL" VARCHAR2(32767), 
	"REGION" VARCHAR2(255), 
	"APEX$SYNC_STEP_STATIC_ID" VARCHAR2(255), 
	"APEX$ROW_SYNC_TIMESTAMP" TIMESTAMP (6) WITH TIME ZONE, 
	 CONSTRAINT "COUNTRIES_PK" PRIMARY KEY ("CCA2")
  USING INDEX  ENABLE
   ) ;